# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-10 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='author',
            new_name='owner',
        ),
    ]
