# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_is_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html',
            field=models.TextField(default='', help_text='\u6ce8\uff1a\u76ee\u524d\u4ec5\u652f\u6301Markdown\u683c\u5f0f\u6570\u636e', verbose_name='\u6e32\u67d3\u540e\u7684\u5185\u5bb9'),
        ),
    ]
